version: '2'
services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    volumes:
     - .:/var/www/html
     - ./php.xdebug.ini:/usr/local/etc/php/php.ini
  db_dm:
    extends:
      file: docker-compose.yml
      service: db_dm
