version: '2'
services:
  web:
    container_name: ducksmanager
    build: .
    ports:
     - "8000:80"
    volumes:
     - .:/var/www/html
     - ./php.xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - dmserver_front-network
  db_dm:
    extends:
      file: docker-compose.yml
      service: db_dm
    volumes:
     - ./schema-populated.sql.gz:/docker-entrypoint-initdb.d/schema-populated.sql.gz:ro
    networks:
      - dmserver_front-network
networks:
  dmserver_front-network:
    external: true